name: Matrix Configuration

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy: 
      # Fail the build if any of the configurations fail
      fail-fast: false 
      # Control the number of parallel jobs
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [hello-world, alpine]
        # Exclude os + images from the matrix
        exclude: 
          - os: windows-latest
            images: alpine
        # Only run the job on the latest version of Ubuntu
        include:
          - images: amd64/alpine
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo Docker Details
        run: docker info
      - name: Run Image on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}

      