name: Exploring Variables and Secrets
on: push
env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: siddharth1
  DOCKER_PASSWORD: s3cUrePaSsw0rd
  IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$env.IMAGE_NAME:latest
      - name: Docker Login
        run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
      - name: Docker Publish
        run: echo docker push $CONTAINER_REGISTRY/$env.DOCKER_USERNAME/$env.IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Docker Run
        run: echo docker run -d -p 80:80 docker.io/$env.DOCKER_USERNAME/$env.IMAGE_NAME:latest
